### ISSUE TITLE
Failed to grant owner status: Bare JID expected, got full JID

### ISSUE THREAD

**Issue by denzill** [jitsi/jicofo#895] opened 2022-03-18 13:31 UTC
### Description:
I install Jitsi-meet by this doc: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstar.
Then enable authentication by this: https://jitsi.github.io/handbook/docs/devops-guide/secure-domain.
And now after create conference i get an error in jicofo.log:

`Jicofo 2022-03-18 16:13:23.094 SEVERE: [118] ChatRoomRoleManager.grantOwner#46: Failed to grant owner status to mpyze6sgt1f5rgcabavcgo5j@guest.jitsi.minsk.isida.by/JayE684PsEBe
java.lang.RuntimeException: Failed to grant owner: <iq xmlns='jabber:client' to='focus@auth.jitsi.minsk.isida.by/focus' from='crowdedphilosopherslistenresponsibly@conference.jitsi.minsk.isida.by' id='BQN8J-179' type='error'><error type='modify'><jid-malformed xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Bare JID expected, got full JID</text></error></iq>
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.grantOwnership(ChatRoomImpl.java:482)
	at org.jitsi.jicofo.xmpp.muc.ChatRoomRoleManager.grantOwner(ChatRoomRoleManager.kt:43)
	at org.jitsi.jicofo.xmpp.muc.AuthenticationRoleManager.authenticationListener$lambda-2(ChatRoomRoleManager.kt:127)
	at org.jitsi.jicofo.auth.AbstractAuthAuthority.notifyUserAuthenticated(AbstractAuthAuthority.java:343)
	at org.jitsi.jicofo.auth.AbstractAuthAuthority.authenticateJidWithSession(AbstractAuthAuthority.java:433)
	at org.jitsi.jicofo.auth.XMPPDomainAuthAuthority.processAuthLocked(XMPPDomainAuthAuthority.java:100)
	at org.jitsi.jicofo.auth.AbstractAuthAuthority.processAuthentication(AbstractAuthAuthority.java:356)
	at org.jitsi.jicofo.xmpp.ConferenceIqHandler.processExtensions(ConferenceIqHandler.kt:118)
	at org.jitsi.jicofo.xmpp.ConferenceIqHandler.handleConferenceIq(ConferenceIqHandler.kt:67)
	at org.jitsi.jicofo.xmpp.ConferenceIqHandler.handleIQRequest$lambda-4(ConferenceIqHandler.kt:156)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

### Expected behavior:
I need moderator rights in conference

### Server information:

- Jitsi Meet version: 0.12
- Operating System: Debian 11

### Client information:

- Browser / app version: Chrome Version 99.0.4844.51 (Official Build) (64-bit)
- Operating System: Ubuntu/Windows

**Comment by saghul** [comment] 2022-03-18 13:59
@damencho Should we report this to Matt? Working with both 0.11 and 0.12 might become a nightmare otherwise?

**Comment by denzill** [comment] 2022-03-18 15:01
> Please downgrade to Prosody 0.11, we have not updated yet to 0.12.

Yes, this is work...

maybe to instructions in section "Install Jitsi Meet" add this?:
`sudo apt install prosody=0.11.9-2+deb11u2`
`sudo apt install jitsi-meet`

show all versions of prosody:
`apt policy prosody`

**Comment by saghul** [comment] 2022-03-18 15:17
> maybe to instructions in section "Install Jitsi Meet" add this?:

The problem is it depends on what repos one has. As in, that won't work on Ubuntu I think.

With Prosody's repos you can install `prosody-0.11` and that will do.

**Comment by damencho** [comment] 2022-03-18 15:17
@saghul Nope, we need to fix it. According to the xep-0045: `Affiliations are granted, revoked, and maintained based on the user’s bare JID, not the nick as with roles.`

**Comment by damencho** [comment] 2022-03-18 15:18
We also need to fix it in the lib-jitsi-meet where we use nick and maybe report that one to Matt, as it is not by xep.

**Comment by saghul** [comment] 2022-03-18 15:21
Ah, gotcha. Opsie.

**Comment by bgrozev** [comment] 2023-01-05 00:21
This should have been fixed in #895 and #896

**Closed by bgrozev** 2023-01-05 00:21 UTC
