### ISSUE TITLE
Deadlock in AbstractAuthAuthority

### ISSUE THREAD

**Issue by jmartine** [jitsi/jicofo#309] opened 2018-08-28 21:51 UTC
## Description
---

I'm seeing a deadlock when using the AbstractAuthAuthority code. This seem to happen when there rapid requests to create a conference are being processed. Here is the out put of a thread dump (I can attach the full dump if that would help):

```
Found one Java-level deadlock:
=============================
"pool-7-thread-17":
  waiting to lock monitor 0x00007f1c780375a8 (object 0x000000070048bdf0, a java.lang.Object),
  which is held by "pool-7-thread-10"
"pool-7-thread-10":
  waiting to lock monitor 0x00007f1c78035ef8 (object 0x0000000782512f08, a java.util.HashMap),
  which is held by "Smack-Single Threaded Executor 0 (0)"
"Smack-Single Threaded Executor 0 (0)":
  waiting to lock monitor 0x00007f1c780375a8 (object 0x000000070048bdf0, a java.lang.Object),
  which is held by "pool-7-thread-10"

Java stack information for the threads listed above:
===================================================
"pool-7-thread-17":
	at org.jitsi.jicofo.auth.AbstractAuthAuthority.processAuthentication(AbstractAuthAuthority.java:347)
	- waiting to lock <0x000000070048bdf0> (a java.lang.Object)
	at org.jitsi.jicofo.xmpp.FocusComponent.processExtensions(FocusComponent.java:292)
	at org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq(FocusComponent.java:343)
	at org.jitsi.jicofo.xmpp.FocusComponent.handleIQSetImpl(FocusComponent.java:221)
	at org.jitsi.xmpp.component.ComponentBase.handleIQSet(ComponentBase.java:362)
	at org.xmpp.component.AbstractComponent.processIQRequest(AbstractComponent.java:515)
	at org.xmpp.component.AbstractComponent.processIQ(AbstractComponent.java:289)
	at org.xmpp.component.AbstractComponent.processQueuedPacket(AbstractComponent.java:239)
	at org.xmpp.component.AbstractComponent.access$100(AbstractComponent.java:81)
	at org.xmpp.component.AbstractComponent$PacketProcessor.run(AbstractComponent.java:1051)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
"pool-7-thread-10":
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.getMembers(ChatRoomImpl.java:597)
	- waiting to lock <0x0000000782512f08> (a java.util.HashMap)
	at org.jitsi.jicofo.ChatRoomRoleAndPresence.jidAuthenticated(ChatRoomRoleAndPresence.java:313)
	at org.jitsi.jicofo.auth.AbstractAuthAuthority.notifyUserAuthenticated(AbstractAuthAuthority.java:336)
	at org.jitsi.jicofo.auth.AbstractAuthAuthority.authenticateJidWithSession(AbstractAuthAuthority.java:413)
	at org.jitsi.jicofo.auth.XMPPDomainAuthAuthority.processAuthLocked(XMPPDomainAuthAuthority.java:98)
	at org.jitsi.jicofo.auth.AbstractAuthAuthority.processAuthentication(AbstractAuthAuthority.java:347)
	- locked <0x000000070048bdf0> (a java.lang.Object)
	at org.jitsi.jicofo.xmpp.FocusComponent.processExtensions(FocusComponent.java:292)
	at org.jitsi.jicofo.xmpp.FocusComponent.handleConferenceIq(FocusComponent.java:343)
	at org.jitsi.jicofo.xmpp.FocusComponent.handleIQSetImpl(FocusComponent.java:221)
	at org.jitsi.xmpp.component.ComponentBase.handleIQSet(ComponentBase.java:362)
	at org.xmpp.component.AbstractComponent.processIQRequest(AbstractComponent.java:515)
	at org.xmpp.component.AbstractComponent.processIQ(AbstractComponent.java:289)
	at org.xmpp.component.AbstractComponent.processQueuedPacket(AbstractComponent.java:239)
	at org.xmpp.component.AbstractComponent.access$100(AbstractComponent.java:81)
	at org.xmpp.component.AbstractComponent$PacketProcessor.run(AbstractComponent.java:1051)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
"Smack-Single Threaded Executor 0 (0)":
	at org.jitsi.jicofo.auth.AbstractAuthAuthority.findSessionForJabberId(AbstractAuthAuthority.java:226)
	- waiting to lock <0x000000070048bdf0> (a java.lang.Object)
	at org.jitsi.jicofo.auth.AbstractAuthAuthority.getSessionForJid(AbstractAuthAuthority.java:251)
	at org.jitsi.jicofo.ChatRoomRoleAndPresence.checkGrantOwnerToAuthUser(ChatRoomRoleAndPresence.java:294)
	at org.jitsi.jicofo.ChatRoomRoleAndPresence.memberPresenceChanged(ChatRoomRoleAndPresence.java:146)
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.lambda$notifyMemberJoined$32(ChatRoomImpl.java:915)
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl$$Lambda$7/204059536.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:890)
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.notifyMemberJoined(ChatRoomImpl.java:915)
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.processOtherPresence(ChatRoomImpl.java:1198)
	- locked <0x0000000782512f08> (a java.util.HashMap)
	at org.jitsi.impl.protocol.xmpp.ChatRoomImpl.processPresence(ChatRoomImpl.java:1239)
	at org.jivesoftware.smackx.muc.MultiUserChat$3.processStanza(MultiUserChat.java:251)
	at org.jivesoftware.smack.AbstractXMPPConnection$5.run(AbstractXMPPConnection.java:1229)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Found 1 deadlock.
``` 
## Current behavior
---

deadlock. And jicofo needs to be restarted.

## Expected Behavior
---

## Possible Solution
---

## Steps to reproduce
---
request create conference requests rapidly. 

# Environment details
---
 Using build 417 of jicofo

**Comment by daimoc** [comment] 2018-09-21 13:39
Hi, 
This deadlock seems to be the same we observe some time in our perform for nearly one year ( It happens once a month).
Thanks for reporting it.

Could you describe what is the behavior of the Jicofo processes when this situation happen (what is in jicofo log) ? 
Are you able to easily reproduce it ?

I notice that you propose a fix, but did you  made some load testing of your proposed solution of removing the synchronization block around the call to  processAuthLocked ?

Does someone in the Jitsi-team knows the reason of this synchronization ?


Best Regards,
Damien

**Comment by paweldomas** [comment] 2018-09-21 18:35
Hi,

I would go with this fix:

https://github.com/jitsi/jicofo/pull/317

**Comment by jmartine** [comment] 2018-09-26 16:02
Thanks @paweldomas !

I currently don't have cycles to try out this but when I do I will test it out on my end.

@daimoc  I was able to reproduce the deadlock by making rapid concurrent requests to jicofo.  Once deadlocked jicofo would be slow or stop in processing request and eventually start dropping videobridges.  That was the behavior that I was experiencing.

**Comment by daimoc** [comment] 2018-10-09 09:01
Any news about fix itergration ?

**Comment by paweldomas** [comment] 2018-10-09 13:58
The Pr is in review and should be merged this week.

**Comment by paweldomas** [comment] 2018-10-16 14:19
The fix is in the master.

**Closed by paweldomas** 2018-10-16 14:19 UTC
